#!/usr/bin/env bash
# dev-setup.sh (OSK-52) — generate a local .env with dev defaults for docker compose.
#
# Why not `cp .env.example .env`? .env.example intentionally carries bare, prod-shaped
# vars (no defaults) so prod misconfig fails loudly — copying it leaves DB_PASSWORD
# blank and compose aborts. This writes a WORKING local .env instead (TM-127).
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$root/.env"
if [ -f "$env_file" ]; then
  echo ".env already exists — leaving it untouched."
  exit 0
fi
cat > "$env_file" <<'ENVEOF'
# Local dev defaults, generated by scripts/dev-setup.sh. Git-ignored; never committed.
POSTGRES_DB=osk
POSTGRES_USER=osk
POSTGRES_PASSWORD=osk
DB_URL=jdbc:postgresql://postgres:5432/osk
DB_USERNAME=osk
DB_PASSWORD=osk
APP_ENVIRONMENT_NAME=dev
APP_PUBLIC_BASE_URL=http://localhost:8080
ENVEOF
echo "Wrote $env_file (dev defaults). Now run: docker compose up"
