package io.openskeleton.backend.version;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.info.BuildProperties;
import org.springframework.http.MediaType;
import org.springframework.lang.Nullable;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Build/version stamp endpoint: {@code GET /version} → {@code 200} JSON reporting
 * which commit + build of the backend is running (OSK-100).
 *
 * <p><b>What it returns:</b> {@code {"sha": ..., "buildTime": ..., "revision": ...}}
 * where {@code sha} is the git commit the running image was built from,
 * {@code buildTime} is when the jar was packaged, and {@code revision} is the Cloud
 * Run per-deploy revision (present only when running on Cloud Run). The web front
 * page fetches this and shows it next to its own build id so a glance at the live
 * site tells you exactly what is deployed on both tiers.
 *
 * <p><b>Why it lives at the root ({@code /version}), NOT under {@code /api/v1}:</b>
 * it must be reachable with no auth — the same way {@code /health} is. The
 * {@link io.openskeleton.backend.auth.FirebaseAuthenticationFilter} guards ONLY the
 * {@code /api/v1/**} prefix (everything else is public by omission), and the
 * {@code /api/v1} URL prefix is applied ONLY to controllers in the {@code api}
 * package (see {@code ApiVersioningConfig}). Placing this controller in its own
 * {@code version} package therefore keeps it both unversioned and unauthenticated —
 * a build/version probe should never require a token, mirroring {@code /health}.
 *
 * <p><b>Why {@code produces = APPLICATION_JSON_VALUE} is pinned:</b> same reason as
 * {@code /health} (TM-126) — force JSON regardless of a browser {@code Accept} header
 * that lists XML, so a later XML converter on the classpath cannot flip this to XML.
 *
 * <p><b>Where the values come from — nothing hardcoded (AC4):</b>
 * <ul>
 *   <li>{@code sha}: the {@code build.git-sha} Spring property, sourced from the
 *       {@code GIT_SHA} env var baked into the image at build time (Dockerfile
 *       {@code ARG GIT_SHA}, wired from {@code github.sha} in {@code image.yml}). If
 *       that is absent (e.g. a bare local {@code mvn spring-boot:run}) it falls back
 *       to the git SHA in Spring Boot's {@link BuildProperties} (from
 *       {@code build-info.properties}) and finally to {@code "unknown"}.</li>
 *   <li>{@code buildTime}: taken from {@link BuildProperties} (generated by the
 *       {@code build-info} goal on the {@code spring-boot-maven-plugin}). {@code null}
 *       when build-info was not generated.</li>
 *   <li>{@code revision}: the {@code build.revision} property, sourced from Cloud
 *       Run's injected {@code K_REVISION} env var; {@code null} off Cloud Run.</li>
 * </ul>
 */
@RestController
public class VersionController {

    /**
     * JSON shape for {@code /version}. A record keeps the contract obvious and
     * immutable. Fields may be {@code null} (e.g. {@code revision} off Cloud Run,
     * {@code buildTime} when build-info is absent); {@code null} fields are still
     * serialised so the shape is stable for the web consumer.
     *
     * @param sha       the git commit the running backend was built from
     * @param buildTime ISO-8601 instant the jar was packaged, or {@code null}
     * @param revision  the Cloud Run revision serving this request, or {@code null}
     */
    public record Version(String sha, String buildTime, String revision) {}

    /** Commit SHA injected into the image at build time (Docker ARG → GIT_SHA env). Blank if unset. */
    private final String gitSha;

    /** Cloud Run per-deploy revision (K_REVISION env). Blank off Cloud Run. */
    private final String revision;

    /** Spring Boot build-info (from build-info.properties), or {@code null} when not generated. */
    private final BuildProperties buildProperties;

    /**
     * @param gitSha the {@code build.git-sha} property (from the {@code GIT_SHA} env
     *     baked into the image); empty when unset — the two {@code @Value} defaults are
     *     empty strings so an unset env var resolves to blank, not a placeholder
     * @param revision the {@code build.revision} property (Cloud Run's {@code K_REVISION});
     *     empty off Cloud Run
     * @param buildProperties Spring Boot build-info, or {@code null}. It is
     *     {@code @Nullable} because the {@code BuildProperties} bean only exists once
     *     the {@code build-info} goal has generated {@code build-info.properties} — so
     *     Spring injects {@code null} in a web slice / a build without build-info rather
     *     than failing to wire the controller. Unit tests use this same constructor
     *     directly to exercise every resolution branch without a Spring context.
     */
    public VersionController(
            @Value("${build.git-sha:}") String gitSha,
            @Value("${build.revision:}") String revision,
            @Nullable BuildProperties buildProperties) {
        this.gitSha = gitSha;
        this.revision = revision;
        this.buildProperties = buildProperties;
    }

    @GetMapping(value = "/version", produces = MediaType.APPLICATION_JSON_VALUE)
    public Version version() {
        return new Version(resolveSha(), resolveBuildTime(), blankToNull(revision));
    }

    /**
     * Resolve the commit SHA: prefer the build-time {@code GIT_SHA} env (the image's
     * authoritative source), then fall back to the SHA recorded in build-info, then a
     * safe {@code "unknown"} sentinel so the endpoint never reports a hardcoded value.
     */
    private String resolveSha() {
        if (isNotBlank(gitSha)) {
            return gitSha;
        }
        if (buildProperties != null) {
            String fromBuildInfo = buildProperties.get("git.sha");
            if (isNotBlank(fromBuildInfo)) {
                return fromBuildInfo;
            }
        }
        return "unknown";
    }

    /** Build timestamp from build-info, or {@code null} when build-info is absent. */
    private String resolveBuildTime() {
        if (buildProperties != null && buildProperties.getTime() != null) {
            return buildProperties.getTime().toString();
        }
        return null;
    }

    private static String blankToNull(String value) {
        return isNotBlank(value) ? value : null;
    }

    private static boolean isNotBlank(String value) {
        return value != null && !value.isBlank();
    }
}
